-- Seed data for public.pharmacies.
-- NOT auto-generated by any migration in the original project — the "name" column
-- must match EXACTLY the `pharmacyName` strings used in the `scrapers[]` registry
-- inside supabase/functions/farma-search/index.ts, or that pharmacy's results are
-- silently dropped (pharmacyIdMap lookup miss).
--
-- shipping_cost / free_shipping_threshold verified against each pharmacy's own site
-- on 2026-07-09. Rows marked TODO need a manual check before going live — a wrong
-- value here silently corrupts the "Totale (con spedizione)" column, it won't error.
--
-- NOTE: public.pharmacies has no UNIQUE constraint on `name`, so this insert is
-- NOT idempotent — run it exactly once, right after the migrations, on a fresh DB.
-- Re-running would create duplicate rows and make pharmacyIdMap lookups ambiguous.

insert into public.pharmacies (name, base_url, search_url_template, shipping_cost, free_shipping_threshold) values
  ('Amicafarmacia', 'https://www.amicafarmacia.com', 'https://www.amicafarmacia.com/search/suggest.json?q={query}&resources[type]=product', 5.90, 69.00),
  ('Farmae', 'https://www.farmae.it', 'https://www.farmae.it/search/suggest.json?q={query}&resources[type]=product', 4.99, 24.90),
  ('Farmacia Guacci', 'https://farmaciaguacci.it', 'https://farmaciaguacci.it/index.php?route=product/search&search={query}', 5.90, 39.90),
  ('Farmacia del Corso', 'https://farmaciadelcorso.net', 'https://farmaciadelcorso.net/index.php?route=product/search&search={query}', 5.90, 39.90),
  ('Farmacia Igea', 'https://www.farmaciaigea.com', 'https://www.farmaciaigea.com/index.php?route=product/search&search={query}', 4.90, 29.00),
  ('eFarma', 'https://efarma.com', 'https://70OAFALOKQ-dsn.algolia.net/1/indexes/pro_efarma_it_products/query', 5.00, 29.90),
  -- TODO: verify before launch — costo/soglia non confermati da fonte ufficiale al momento della stesura.
  ('1000Farmacie', 'https://www.1000farmacie.it', 'https://hw3t8wvs73-dsn.algolia.net/1/indexes/Product/query', 0, null),
  ('Farmacia Gaudiana', 'https://farmaciagaudiana.it', 'https://farmaciagaudiana.it/index.php?route=product/search&search={query}', 0, null),
  ('Farmacia Uno', 'https://farmaciauno.it', 'https://open.seken.ai/api/search', 0, null),
  -- NB: farmaeurope.eu ora reindirizza a farmae.it (i due brand si sono fusi) — vedi
  -- README-MIGRATION.md per la valutazione se vale ancora la pena tenere questo scraper.
  ('Farmaeurope', 'https://www.farmaeurope.eu', 'https://www.farmaeurope.eu/searchautocomplete/ajax/suggest/?q={query}', 0, null);
